language: python

python:
  - '2.6'

env:
  - TOXENV=py25,py26,py27

matrix:
  allow_failures:
    - env: TOXENV=py25,py27

# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r requirments.txt
#  - pip install tox

# command to run tests
script:
#  - tox
  - python setup.py tests